import { config } from "@fortawesome/fontawesome-svg-core"
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core"

// Prevent FA from dynamically inserting <style> tags (breaks SSR hydration)
config.autoAddCss = false

// --- Solid icons ---
import {
	faArrowDown,
	faArrowDownToBracket,
	faArrowLeft,
	faArrowRight,
	faArrowRightFromBracket,
	faArrowRotateRight,
	faArrowsUpDown,
	faArrowUp,
	faArrowUpRight,
	faArrowUpRightFromSquare,
	faAt,
	faBagShopping,
	faBars,
	faBell,
	faBook,
	faBookmark,
	faCalendar,
	faCamera,
	faCaretDown,
	faCaretUp,
	faCheck,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faCircle,
	faCircleArrowUpRight,
	faCircleCheck,
	faCircleExclamation,
	faCircleInfo,
	faCirclePlus,
	faCircleQuestion,
	faCircleUserCirclePlus,
	faCircleXmark,
	faClock,
	faClockRotateLeft,
	faCloudArrowUp,
	faCoins,
	faComment,
	faComments,
	faCompass,
	faCube,
	faDownload,
	faEllipsisVertical,
	faEnvelope,
	faExclamation,
	faEye,
	faEyeSlash,
	faFile,
	faFileContract,
	faFilePdf,
	faFileZipper,
	faFire,
	faFlag,
	faFolder,
	faFolderXmark,
	faGear,
	faGem,
	faGrid2,
	faHashtag,
	faHeart,
	faHexagonImage,
	faHouse,
	faImage,
	faImages,
	faImageSlash,
	faImageStack,
	faInfo,
	faKey,
	faLayerGroup,
	faLifeRing,
	faLinkSimple,
	faList,
	faListUl,
	faLock,
	faMagnifyingGlass,
	faMessage,
	faMessageLines,
	faMessageSlash,
	faMobileScreenButton,
	faMoon,
	faMusic,
	faPalette,
	faPaperPlane,
	faPause,
	faPencil,
	faPlay,
	faPlus,
	faRightToBracket,
	faRocket,
	faShield,
	faShieldCheck,
	faShieldHalved,
	faSparkles,
	faSpinner,
	faSpinnerThird,
	faStar,
	faSunBright,
	faTag,
	faTrashXmark,
	faTriangleExclamation,
	faUser,
	faUserCheck,
	faUserGear,
	faUserMinus,
	faUserPen,
	faUserPlus,
	faUsers,
	faUserSlash,
	faVideo,
	faVideoSlash,
	faVolumeHigh,
	faVolumeXmark,
	faWallet,
	faWifiSlash,
	faXmark,
} from "@fortawesome/pro-solid-svg-icons"

// --- Regular icons (aliased with far prefix) ---
import {
	faArrowDown as farArrowDown,
	faArrowDownToBracket as farArrowDownToBracket,
	faArrowLeft as farArrowLeft,
	faArrowRight as farArrowRight,
	faArrowRightFromBracket as farArrowRightFromBracket,
	faArrowRotateRight as farArrowRotateRight,
	faArrowsUpDown as farArrowsUpDown,
	faArrowUp as farArrowUp,
	faArrowUpRight as farArrowUpRight,
	faArrowUpRightFromSquare as farArrowUpRightFromSquare,
	faAt as farAt,
	faBagShopping as farBagShopping,
	faBars as farBars,
	faBell as farBell,
	faBook as farBook,
	faBookmark as farBookmark,
	faCalendar as farCalendar,
	faCamera as farCamera,
	faCaretDown as farCaretDown,
	faCaretUp as farCaretUp,
	faCheck as farCheck,
	faChevronDown as farChevronDown,
	faChevronLeft as farChevronLeft,
	faChevronRight as farChevronRight,
	faChevronUp as farChevronUp,
	faCircle as farCircle,
	faCircleArrowUpRight as farCircleArrowUpRight,
	faCircleCheck as farCircleCheck,
	faCircleExclamation as farCircleExclamation,
	faCircleInfo as farCircleInfo,
	faCirclePlus as farCirclePlus,
	faCircleQuestion as farCircleQuestion,
	faCircleUserCirclePlus as farCircleUserCirclePlus,
	faCircleXmark as farCircleXmark,
	faClock as farClock,
	faClockRotateLeft as farClockRotateLeft,
	faCloudArrowUp as farCloudArrowUp,
	faCoins as farCoins,
	faComment as farComment,
	faComments as farComments,
	faCompass as farCompass,
	faCube as farCube,
	faDownload as farDownload,
	faEllipsisVertical as farEllipsisVertical,
	faEnvelope as farEnvelope,
	faExclamation as farExclamation,
	faEye as farEye,
	faEyeSlash as farEyeSlash,
	faFile as farFile,
	faFileContract as farFileContract,
	faFilePdf as farFilePdf,
	faFileZipper as farFileZipper,
	faFire as farFire,
	faFlag as farFlag,
	faFolder as farFolder,
	faFolderXmark as farFolderXmark,
	faGear as farGear,
	faGem as farGem,
	faGrid2 as farGrid2,
	faHashtag as farHashtag,
	faHeart as farHeart,
	faHexagonImage as farHexagonImage,
	faHouse as farHouse,
	faImage as farImage,
	faImages as farImages,
	faImageSlash as farImageSlash,
	faImageStack as farImageStack,
	faInfo as farInfo,
	faKey as farKey,
	faLayerGroup as farLayerGroup,
	faLifeRing as farLifeRing,
	faLinkSimple as farLinkSimple,
	faList as farList,
	faListUl as farListUl,
	faLock as farLock,
	faMagnifyingGlass as farMagnifyingGlass,
	faMessage as farMessage,
	faMessageLines as farMessageLines,
	faMessageSlash as farMessageSlash,
	faMobileScreenButton as farMobileScreenButton,
	faMoon as farMoon,
	faMusic as farMusic,
	faPalette as farPalette,
	faPaperPlane as farPaperPlane,
	faPause as farPause,
	faPencil as farPencil,
	faPlay as farPlay,
	faPlus as farPlus,
	faRightToBracket as farRightToBracket,
	faRocket as farRocket,
	faShield as farShield,
	faShieldCheck as farShieldCheck,
	faShieldHalved as farShieldHalved,
	faSparkles as farSparkles,
	faSpinner as farSpinner,
	faSpinnerThird as farSpinnerThird,
	faStar as farStar,
	faSunBright as farSunBright,
	faTag as farTag,
	faTrashXmark as farTrashXmark,
	faTriangleExclamation as farTriangleExclamation,
	faUser as farUser,
	faUserCheck as farUserCheck,
	faUserGear as farUserGear,
	faUserMinus as farUserMinus,
	faUserPen as farUserPen,
	faUserPlus as farUserPlus,
	faUsers as farUsers,
	faUserSlash as farUserSlash,
	faVideo as farVideo,
	faVideoSlash as farVideoSlash,
	faVolumeHigh as farVolumeHigh,
	faVolumeXmark as farVolumeXmark,
	faWallet as farWallet,
	faWifiSlash as farWifiSlash,
	faXmark as farXmark,
} from "@fortawesome/pro-regular-svg-icons"

// --- Brand icons ---
import {
	faGoogle,
	faXTwitter,
} from "@fortawesome/free-brands-svg-icons"

// --- Icon registries ---

export const solidIcons: Record<string, IconDefinition> = {
	"arrow-down": faArrowDown,
	"arrow-down-to-bracket": faArrowDownToBracket,
	"arrow-left": faArrowLeft,
	"arrow-right": faArrowRight,
	"arrow-right-from-bracket": faArrowRightFromBracket,
	"arrow-rotate-right": faArrowRotateRight,
	"arrows-up-down": faArrowsUpDown,
	"arrow-up": faArrowUp,
	"arrow-up-right": faArrowUpRight,
	"arrow-up-right-from-square": faArrowUpRightFromSquare,
	"at": faAt,
	"bag-shopping": faBagShopping,
	"bars": faBars,
	"bell": faBell,
	"book": faBook,
	"bookmark": faBookmark,
	"calendar": faCalendar,
	"camera": faCamera,
	"caret-down": faCaretDown,
	"caret-up": faCaretUp,
	"check": faCheck,
	"chevron-down": faChevronDown,
	"chevron-left": faChevronLeft,
	"chevron-right": faChevronRight,
	"chevron-up": faChevronUp,
	"circle": faCircle,
	"circle-arrow-up-right": faCircleArrowUpRight,
	"circle-check": faCircleCheck,
	"circle-exclamation": faCircleExclamation,
	"circle-info": faCircleInfo,
	"circle-plus": faCirclePlus,
	"circle-question": faCircleQuestion,
	"circle-user-circle-plus": faCircleUserCirclePlus,
	"circle-xmark": faCircleXmark,
	"clock": faClock,
	"clock-rotate-left": faClockRotateLeft,
	"cloud-arrow-up": faCloudArrowUp,
	"coins": faCoins,
	"comment": faComment,
	"comments": faComments,
	"compass": faCompass,
	"cube": faCube,
	"download": faDownload,
	"ellipsis-vertical": faEllipsisVertical,
	"envelope": faEnvelope,
	"exclamation": faExclamation,
	"eye": faEye,
	"eye-slash": faEyeSlash,
	"file": faFile,
	"file-contract": faFileContract,
	"file-pdf": faFilePdf,
	"file-zipper": faFileZipper,
	"fire": faFire,
	"flag": faFlag,
	"folder": faFolder,
	"folder-xmark": faFolderXmark,
	"gear": faGear,
	"gem": faGem,
	"grid-2": faGrid2,
	"hashtag": faHashtag,
	"heart": faHeart,
	"hexagon-image": faHexagonImage,
	"house": faHouse,
	"image": faImage,
	"images": faImages,
	"image-slash": faImageSlash,
	"image-stack": faImageStack,
	"info": faInfo,
	"key": faKey,
	"layer-group": faLayerGroup,
	"life-ring": faLifeRing,
	"link-simple": faLinkSimple,
	"list": faList,
	"list-ul": faListUl,
	"lock": faLock,
	"magnifying-glass": faMagnifyingGlass,
	"message": faMessage,
	"message-lines": faMessageLines,
	"message-slash": faMessageSlash,
	"mobile-screen-button": faMobileScreenButton,
	"moon": faMoon,
	"music": faMusic,
	"palette": faPalette,
	"paper-plane": faPaperPlane,
	"pause": faPause,
	"pencil": faPencil,
	"play": faPlay,
	"plus": faPlus,
	"right-to-bracket": faRightToBracket,
	"rocket": faRocket,
	"shield": faShield,
	"shield-check": faShieldCheck,
	"shield-halved": faShieldHalved,
	"sparkles": faSparkles,
	"spinner": faSpinner,
	"spinner-third": faSpinnerThird,
	"star": faStar,
	"sun-bright": faSunBright,
	"tag": faTag,
	"trash-xmark": faTrashXmark,
	"triangle-exclamation": faTriangleExclamation,
	"user": faUser,
	"user-check": faUserCheck,
	"user-gear": faUserGear,
	"user-minus": faUserMinus,
	"user-pen": faUserPen,
	"user-plus": faUserPlus,
	"users": faUsers,
	"user-slash": faUserSlash,
	"video": faVideo,
	"video-slash": faVideoSlash,
	"volume-high": faVolumeHigh,
	"volume-xmark": faVolumeXmark,
	"wallet": faWallet,
	"wifi-slash": faWifiSlash,
	"xmark": faXmark,
	// Aliases
	"search": faMagnifyingGlass,
	"external-link": faArrowUpRightFromSquare,
	"check-circle": faCircleCheck,
}

export const regularIcons: Record<string, IconDefinition> = {
	"arrow-down": farArrowDown,
	"arrow-down-to-bracket": farArrowDownToBracket,
	"arrow-left": farArrowLeft,
	"arrow-right": farArrowRight,
	"arrow-right-from-bracket": farArrowRightFromBracket,
	"arrow-rotate-right": farArrowRotateRight,
	"arrows-up-down": farArrowsUpDown,
	"arrow-up": farArrowUp,
	"arrow-up-right": farArrowUpRight,
	"arrow-up-right-from-square": farArrowUpRightFromSquare,
	"at": farAt,
	"bag-shopping": farBagShopping,
	"bars": farBars,
	"bell": farBell,
	"book": farBook,
	"bookmark": farBookmark,
	"calendar": farCalendar,
	"camera": farCamera,
	"caret-down": farCaretDown,
	"caret-up": farCaretUp,
	"check": farCheck,
	"chevron-down": farChevronDown,
	"chevron-left": farChevronLeft,
	"chevron-right": farChevronRight,
	"chevron-up": farChevronUp,
	"circle": farCircle,
	"circle-arrow-up-right": farCircleArrowUpRight,
	"circle-check": farCircleCheck,
	"circle-exclamation": farCircleExclamation,
	"circle-info": farCircleInfo,
	"circle-plus": farCirclePlus,
	"circle-question": farCircleQuestion,
	"circle-user-circle-plus": farCircleUserCirclePlus,
	"circle-xmark": farCircleXmark,
	"clock": farClock,
	"clock-rotate-left": farClockRotateLeft,
	"cloud-arrow-up": farCloudArrowUp,
	"coins": farCoins,
	"comment": farComment,
	"comments": farComments,
	"compass": farCompass,
	"cube": farCube,
	"download": farDownload,
	"ellipsis-vertical": farEllipsisVertical,
	"envelope": farEnvelope,
	"exclamation": farExclamation,
	"eye": farEye,
	"eye-slash": farEyeSlash,
	"file": farFile,
	"file-contract": farFileContract,
	"file-pdf": farFilePdf,
	"file-zipper": farFileZipper,
	"fire": farFire,
	"flag": farFlag,
	"folder": farFolder,
	"folder-xmark": farFolderXmark,
	"gear": farGear,
	"gem": farGem,
	"grid-2": farGrid2,
	"hashtag": farHashtag,
	"heart": farHeart,
	"hexagon-image": farHexagonImage,
	"house": farHouse,
	"image": farImage,
	"images": farImages,
	"image-slash": farImageSlash,
	"image-stack": farImageStack,
	"info": farInfo,
	"key": farKey,
	"layer-group": farLayerGroup,
	"life-ring": farLifeRing,
	"link-simple": farLinkSimple,
	"list": farList,
	"list-ul": farListUl,
	"lock": farLock,
	"magnifying-glass": farMagnifyingGlass,
	"message": farMessage,
	"message-lines": farMessageLines,
	"message-slash": farMessageSlash,
	"mobile-screen-button": farMobileScreenButton,
	"moon": farMoon,
	"music": farMusic,
	"palette": farPalette,
	"paper-plane": farPaperPlane,
	"pause": farPause,
	"pencil": farPencil,
	"play": farPlay,
	"plus": farPlus,
	"right-to-bracket": farRightToBracket,
	"rocket": farRocket,
	"shield": farShield,
	"shield-check": farShieldCheck,
	"shield-halved": farShieldHalved,
	"sparkles": farSparkles,
	"spinner": farSpinner,
	"spinner-third": farSpinnerThird,
	"star": farStar,
	"sun-bright": farSunBright,
	"tag": farTag,
	"trash-xmark": farTrashXmark,
	"triangle-exclamation": farTriangleExclamation,
	"user": farUser,
	"user-check": farUserCheck,
	"user-gear": farUserGear,
	"user-minus": farUserMinus,
	"user-pen": farUserPen,
	"user-plus": farUserPlus,
	"users": farUsers,
	"user-slash": farUserSlash,
	"video": farVideo,
	"video-slash": farVideoSlash,
	"volume-high": farVolumeHigh,
	"volume-xmark": farVolumeXmark,
	"wallet": farWallet,
	"wifi-slash": farWifiSlash,
	"xmark": farXmark,
	// Aliases
	"search": farMagnifyingGlass,
	"external-link": farArrowUpRightFromSquare,
	"check-circle": farCircleCheck,
}

export const brandIcons: Record<string, IconDefinition> = {
	"google": faGoogle,
	"x-twitter": faXTwitter,
}

export type IconVariant = "solid" | "regular" | "brands"

export function resolveIcon(
	name: string,
	variant: IconVariant = "solid",
): IconDefinition | undefined {
	const cleanName = name.replace(/^fa-/, "")
	const map =
		variant === "brands"
			? brandIcons
			: variant === "regular"
				? regularIcons
				: solidIcons
	return map[cleanName]
}
