/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TagTagSlugRouteImport } from './routes/tag/$tagSlug'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsHelpRouteImport } from './routes/settings/help'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ProfileSlugRouteImport } from './routes/profile/$slug'
import { Route as PostPostIdRouteImport } from './routes/post/$postId'
import { Route as DevWalletTestRouteImport } from './routes/dev/wallet-test'
import { Route as DevToastTestRouteImport } from './routes/dev/toast-test'
import { Route as DevInputsTestRouteImport } from './routes/dev/inputs-test'
import { Route as DevDbTestRouteImport } from './routes/dev/db-test'
import { Route as DevColorsTestRouteImport } from './routes/dev/colors-test'
import { Route as DevButtonTestRouteImport } from './routes/dev/button-test'
import { Route as DevBadgesTestRouteImport } from './routes/dev/badges-test'
import { Route as DevAuthTestRouteImport } from './routes/dev/auth-test'
import { Route as CategoryCategorySlugRouteImport } from './routes/category/$categorySlug'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as SettingsAccountIndexRouteImport } from './routes/settings/account/index'
import { Route as SettingsAccountWalletsRouteImport } from './routes/settings/account/wallets'
import { Route as SettingsAccountSecurityRouteImport } from './routes/settings/account/security'
import { Route as SettingsAccountProfileInfoRouteImport } from './routes/settings/account/profile-info'
import { Route as SettingsAccountNotificationsRouteImport } from './routes/settings/account/notifications'
import { Route as SettingsAccountMessagingRouteImport } from './routes/settings/account/messaging'
import { Route as SettingsAccountAppRouteImport } from './routes/settings/account/app'
import { Route as PostPostIdEditRouteImport } from './routes/post/$postId/edit'
import { Route as AdminModerationReportIdRouteImport } from './routes/admin/moderation/$reportId'
import { Route as AdminFeedbackFeedbackIdRouteImport } from './routes/admin/feedback/$feedbackId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagTagSlugRoute = TagTagSlugRouteImport.update({
  id: '/tag/$tagSlug',
  path: '/tag/$tagSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWalletTestRoute = DevWalletTestRouteImport.update({
  id: '/dev/wallet-test',
  path: '/dev/wallet-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToastTestRoute = DevToastTestRouteImport.update({
  id: '/dev/toast-test',
  path: '/dev/toast-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevInputsTestRoute = DevInputsTestRouteImport.update({
  id: '/dev/inputs-test',
  path: '/dev/inputs-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDbTestRoute = DevDbTestRouteImport.update({
  id: '/dev/db-test',
  path: '/dev/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevColorsTestRoute = DevColorsTestRouteImport.update({
  id: '/dev/colors-test',
  path: '/dev/colors-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevButtonTestRoute = DevButtonTestRouteImport.update({
  id: '/dev/button-test',
  path: '/dev/button-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBadgesTestRoute = DevBadgesTestRouteImport.update({
  id: '/dev/badges-test',
  path: '/dev/badges-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAuthTestRoute = DevAuthTestRouteImport.update({
  id: '/dev/auth-test',
  path: '/dev/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsAccountIndexRoute = SettingsAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsAccountRoute,
} as any)
const SettingsAccountWalletsRoute = SettingsAccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => SettingsAccountRoute,
} as any)
const SettingsAccountSecurityRoute = SettingsAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsAccountRoute,
} as any)
const SettingsAccountProfileInfoRoute =
  SettingsAccountProfileInfoRouteImport.update({
    id: '/profile-info',
    path: '/profile-info',
    getParentRoute: () => SettingsAccountRoute,
  } as any)
const SettingsAccountNotificationsRoute =
  SettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsAccountRoute,
  } as any)
const SettingsAccountMessagingRoute =
  SettingsAccountMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => SettingsAccountRoute,
  } as any)
const SettingsAccountAppRoute = SettingsAccountAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => SettingsAccountRoute,
} as any)
const PostPostIdEditRoute = PostPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostPostIdRoute,
} as any)
const AdminModerationReportIdRoute = AdminModerationReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AdminModerationRoute,
} as any)
const AdminFeedbackFeedbackIdRoute = AdminFeedbackFeedbackIdRouteImport.update({
  id: '/$feedbackId',
  path: '/$feedbackId',
  getParentRoute: () => AdminFeedbackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/dev/auth-test': typeof DevAuthTestRoute
  '/dev/badges-test': typeof DevBadgesTestRoute
  '/dev/button-test': typeof DevButtonTestRoute
  '/dev/colors-test': typeof DevColorsTestRoute
  '/dev/db-test': typeof DevDbTestRoute
  '/dev/inputs-test': typeof DevInputsTestRoute
  '/dev/toast-test': typeof DevToastTestRoute
  '/dev/wallet-test': typeof DevWalletTestRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/profile/$slug': typeof ProfileSlugRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/help': typeof SettingsHelpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tagSlug': typeof TagTagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/create/': typeof CreateIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/moderation/$reportId': typeof AdminModerationReportIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/settings/account/app': typeof SettingsAccountAppRoute
  '/settings/account/messaging': typeof SettingsAccountMessagingRoute
  '/settings/account/notifications': typeof SettingsAccountNotificationsRoute
  '/settings/account/profile-info': typeof SettingsAccountProfileInfoRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/account/wallets': typeof SettingsAccountWalletsRoute
  '/settings/account/': typeof SettingsAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/dev/auth-test': typeof DevAuthTestRoute
  '/dev/badges-test': typeof DevBadgesTestRoute
  '/dev/button-test': typeof DevButtonTestRoute
  '/dev/colors-test': typeof DevColorsTestRoute
  '/dev/db-test': typeof DevDbTestRoute
  '/dev/inputs-test': typeof DevInputsTestRoute
  '/dev/toast-test': typeof DevToastTestRoute
  '/dev/wallet-test': typeof DevWalletTestRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/profile/$slug': typeof ProfileSlugRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tagSlug': typeof TagTagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/create': typeof CreateIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/moderation/$reportId': typeof AdminModerationReportIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/settings/account/app': typeof SettingsAccountAppRoute
  '/settings/account/messaging': typeof SettingsAccountMessagingRoute
  '/settings/account/notifications': typeof SettingsAccountNotificationsRoute
  '/settings/account/profile-info': typeof SettingsAccountProfileInfoRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/account/wallets': typeof SettingsAccountWalletsRoute
  '/settings/account': typeof SettingsAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/feedback': typeof AdminFeedbackRouteWithChildren
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/dev/auth-test': typeof DevAuthTestRoute
  '/dev/badges-test': typeof DevBadgesTestRoute
  '/dev/button-test': typeof DevButtonTestRoute
  '/dev/colors-test': typeof DevColorsTestRoute
  '/dev/db-test': typeof DevDbTestRoute
  '/dev/inputs-test': typeof DevInputsTestRoute
  '/dev/toast-test': typeof DevToastTestRoute
  '/dev/wallet-test': typeof DevWalletTestRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/profile/$slug': typeof ProfileSlugRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/help': typeof SettingsHelpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tag/$tagSlug': typeof TagTagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/create/': typeof CreateIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/admin/moderation/$reportId': typeof AdminModerationReportIdRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/settings/account/app': typeof SettingsAccountAppRoute
  '/settings/account/messaging': typeof SettingsAccountMessagingRoute
  '/settings/account/notifications': typeof SettingsAccountNotificationsRoute
  '/settings/account/profile-info': typeof SettingsAccountProfileInfoRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/account/wallets': typeof SettingsAccountWalletsRoute
  '/settings/account/': typeof SettingsAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/changelog'
    | '/explore'
    | '/fees'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/feedback'
    | '/admin/moderation'
    | '/category/$categorySlug'
    | '/dev/auth-test'
    | '/dev/badges-test'
    | '/dev/button-test'
    | '/dev/colors-test'
    | '/dev/db-test'
    | '/dev/inputs-test'
    | '/dev/toast-test'
    | '/dev/wallet-test'
    | '/post/$postId'
    | '/profile/$slug'
    | '/settings/account'
    | '/settings/help'
    | '/settings/profile'
    | '/tag/$tagSlug'
    | '/admin/'
    | '/create/'
    | '/profile/'
    | '/settings/'
    | '/admin/feedback/$feedbackId'
    | '/admin/moderation/$reportId'
    | '/post/$postId/edit'
    | '/settings/account/app'
    | '/settings/account/messaging'
    | '/settings/account/notifications'
    | '/settings/account/profile-info'
    | '/settings/account/security'
    | '/settings/account/wallets'
    | '/settings/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/changelog'
    | '/explore'
    | '/fees'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/feedback'
    | '/admin/moderation'
    | '/category/$categorySlug'
    | '/dev/auth-test'
    | '/dev/badges-test'
    | '/dev/button-test'
    | '/dev/colors-test'
    | '/dev/db-test'
    | '/dev/inputs-test'
    | '/dev/toast-test'
    | '/dev/wallet-test'
    | '/post/$postId'
    | '/profile/$slug'
    | '/settings/help'
    | '/settings/profile'
    | '/tag/$tagSlug'
    | '/admin'
    | '/create'
    | '/profile'
    | '/settings'
    | '/admin/feedback/$feedbackId'
    | '/admin/moderation/$reportId'
    | '/post/$postId/edit'
    | '/settings/account/app'
    | '/settings/account/messaging'
    | '/settings/account/notifications'
    | '/settings/account/profile-info'
    | '/settings/account/security'
    | '/settings/account/wallets'
    | '/settings/account'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/changelog'
    | '/explore'
    | '/fees'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin/feedback'
    | '/admin/moderation'
    | '/category/$categorySlug'
    | '/dev/auth-test'
    | '/dev/badges-test'
    | '/dev/button-test'
    | '/dev/colors-test'
    | '/dev/db-test'
    | '/dev/inputs-test'
    | '/dev/toast-test'
    | '/dev/wallet-test'
    | '/post/$postId'
    | '/profile/$slug'
    | '/settings/account'
    | '/settings/help'
    | '/settings/profile'
    | '/tag/$tagSlug'
    | '/admin/'
    | '/create/'
    | '/profile/'
    | '/settings/'
    | '/admin/feedback/$feedbackId'
    | '/admin/moderation/$reportId'
    | '/post/$postId/edit'
    | '/settings/account/app'
    | '/settings/account/messaging'
    | '/settings/account/notifications'
    | '/settings/account/profile-info'
    | '/settings/account/security'
    | '/settings/account/wallets'
    | '/settings/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ExploreRoute: typeof ExploreRoute
  FeesRoute: typeof FeesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  DevAuthTestRoute: typeof DevAuthTestRoute
  DevBadgesTestRoute: typeof DevBadgesTestRoute
  DevButtonTestRoute: typeof DevButtonTestRoute
  DevColorsTestRoute: typeof DevColorsTestRoute
  DevDbTestRoute: typeof DevDbTestRoute
  DevInputsTestRoute: typeof DevInputsTestRoute
  DevToastTestRoute: typeof DevToastTestRoute
  DevWalletTestRoute: typeof DevWalletTestRoute
  PostPostIdRoute: typeof PostPostIdRouteWithChildren
  ProfileSlugRoute: typeof ProfileSlugRoute
  SettingsAccountRoute: typeof SettingsAccountRouteWithChildren
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  TagTagSlugRoute: typeof TagTagSlugRoute
  CreateIndexRoute: typeof CreateIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tag/$tagSlug': {
      id: '/tag/$tagSlug'
      path: '/tag/$tagSlug'
      fullPath: '/tag/$tagSlug'
      preLoaderRoute: typeof TagTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/help': {
      id: '/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/wallet-test': {
      id: '/dev/wallet-test'
      path: '/dev/wallet-test'
      fullPath: '/dev/wallet-test'
      preLoaderRoute: typeof DevWalletTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/toast-test': {
      id: '/dev/toast-test'
      path: '/dev/toast-test'
      fullPath: '/dev/toast-test'
      preLoaderRoute: typeof DevToastTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/inputs-test': {
      id: '/dev/inputs-test'
      path: '/dev/inputs-test'
      fullPath: '/dev/inputs-test'
      preLoaderRoute: typeof DevInputsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/db-test': {
      id: '/dev/db-test'
      path: '/dev/db-test'
      fullPath: '/dev/db-test'
      preLoaderRoute: typeof DevDbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/colors-test': {
      id: '/dev/colors-test'
      path: '/dev/colors-test'
      fullPath: '/dev/colors-test'
      preLoaderRoute: typeof DevColorsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/button-test': {
      id: '/dev/button-test'
      path: '/dev/button-test'
      fullPath: '/dev/button-test'
      preLoaderRoute: typeof DevButtonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/badges-test': {
      id: '/dev/badges-test'
      path: '/dev/badges-test'
      fullPath: '/dev/badges-test'
      preLoaderRoute: typeof DevBadgesTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/auth-test': {
      id: '/dev/auth-test'
      path: '/dev/auth-test'
      fullPath: '/dev/auth-test'
      preLoaderRoute: typeof DevAuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/account/': {
      id: '/settings/account/'
      path: '/'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof SettingsAccountIndexRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/wallets': {
      id: '/settings/account/wallets'
      path: '/wallets'
      fullPath: '/settings/account/wallets'
      preLoaderRoute: typeof SettingsAccountWalletsRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/security': {
      id: '/settings/account/security'
      path: '/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof SettingsAccountSecurityRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/profile-info': {
      id: '/settings/account/profile-info'
      path: '/profile-info'
      fullPath: '/settings/account/profile-info'
      preLoaderRoute: typeof SettingsAccountProfileInfoRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/notifications': {
      id: '/settings/account/notifications'
      path: '/notifications'
      fullPath: '/settings/account/notifications'
      preLoaderRoute: typeof SettingsAccountNotificationsRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/messaging': {
      id: '/settings/account/messaging'
      path: '/messaging'
      fullPath: '/settings/account/messaging'
      preLoaderRoute: typeof SettingsAccountMessagingRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/account/app': {
      id: '/settings/account/app'
      path: '/app'
      fullPath: '/settings/account/app'
      preLoaderRoute: typeof SettingsAccountAppRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/post/$postId/edit': {
      id: '/post/$postId/edit'
      path: '/edit'
      fullPath: '/post/$postId/edit'
      preLoaderRoute: typeof PostPostIdEditRouteImport
      parentRoute: typeof PostPostIdRoute
    }
    '/admin/moderation/$reportId': {
      id: '/admin/moderation/$reportId'
      path: '/$reportId'
      fullPath: '/admin/moderation/$reportId'
      preLoaderRoute: typeof AdminModerationReportIdRouteImport
      parentRoute: typeof AdminModerationRoute
    }
    '/admin/feedback/$feedbackId': {
      id: '/admin/feedback/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/admin/feedback/$feedbackId'
      preLoaderRoute: typeof AdminFeedbackFeedbackIdRouteImport
      parentRoute: typeof AdminFeedbackRoute
    }
  }
}

interface AdminFeedbackRouteChildren {
  AdminFeedbackFeedbackIdRoute: typeof AdminFeedbackFeedbackIdRoute
}

const AdminFeedbackRouteChildren: AdminFeedbackRouteChildren = {
  AdminFeedbackFeedbackIdRoute: AdminFeedbackFeedbackIdRoute,
}

const AdminFeedbackRouteWithChildren = AdminFeedbackRoute._addFileChildren(
  AdminFeedbackRouteChildren,
)

interface AdminModerationRouteChildren {
  AdminModerationReportIdRoute: typeof AdminModerationReportIdRoute
}

const AdminModerationRouteChildren: AdminModerationRouteChildren = {
  AdminModerationReportIdRoute: AdminModerationReportIdRoute,
}

const AdminModerationRouteWithChildren = AdminModerationRoute._addFileChildren(
  AdminModerationRouteChildren,
)

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRouteWithChildren
  AdminModerationRoute: typeof AdminModerationRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRouteWithChildren,
  AdminModerationRoute: AdminModerationRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PostPostIdRouteChildren {
  PostPostIdEditRoute: typeof PostPostIdEditRoute
}

const PostPostIdRouteChildren: PostPostIdRouteChildren = {
  PostPostIdEditRoute: PostPostIdEditRoute,
}

const PostPostIdRouteWithChildren = PostPostIdRoute._addFileChildren(
  PostPostIdRouteChildren,
)

interface SettingsAccountRouteChildren {
  SettingsAccountAppRoute: typeof SettingsAccountAppRoute
  SettingsAccountMessagingRoute: typeof SettingsAccountMessagingRoute
  SettingsAccountNotificationsRoute: typeof SettingsAccountNotificationsRoute
  SettingsAccountProfileInfoRoute: typeof SettingsAccountProfileInfoRoute
  SettingsAccountSecurityRoute: typeof SettingsAccountSecurityRoute
  SettingsAccountWalletsRoute: typeof SettingsAccountWalletsRoute
  SettingsAccountIndexRoute: typeof SettingsAccountIndexRoute
}

const SettingsAccountRouteChildren: SettingsAccountRouteChildren = {
  SettingsAccountAppRoute: SettingsAccountAppRoute,
  SettingsAccountMessagingRoute: SettingsAccountMessagingRoute,
  SettingsAccountNotificationsRoute: SettingsAccountNotificationsRoute,
  SettingsAccountProfileInfoRoute: SettingsAccountProfileInfoRoute,
  SettingsAccountSecurityRoute: SettingsAccountSecurityRoute,
  SettingsAccountWalletsRoute: SettingsAccountWalletsRoute,
  SettingsAccountIndexRoute: SettingsAccountIndexRoute,
}

const SettingsAccountRouteWithChildren = SettingsAccountRoute._addFileChildren(
  SettingsAccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ExploreRoute: ExploreRoute,
  FeesRoute: FeesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  DevAuthTestRoute: DevAuthTestRoute,
  DevBadgesTestRoute: DevBadgesTestRoute,
  DevButtonTestRoute: DevButtonTestRoute,
  DevColorsTestRoute: DevColorsTestRoute,
  DevDbTestRoute: DevDbTestRoute,
  DevInputsTestRoute: DevInputsTestRoute,
  DevToastTestRoute: DevToastTestRoute,
  DevWalletTestRoute: DevWalletTestRoute,
  PostPostIdRoute: PostPostIdRouteWithChildren,
  ProfileSlugRoute: ProfileSlugRoute,
  SettingsAccountRoute: SettingsAccountRouteWithChildren,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  TagTagSlugRoute: TagTagSlugRoute,
  CreateIndexRoute: CreateIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
